import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Toast from "@/(Providers)/Toast";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  uploadModal,
}: Readonly<{
  children: React.ReactNode;
  uploadModal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toast>
          <Navbar />
          {children}
          {uploadModal}
        </Toast>
      </body>
    </html>
  );
}
